### ISSUE TITLE
mocha 测试时如何使用 jquery.ajax?

### ISSUE THREAD

**Issue by kokokele** [ruanyf/react-testing-demo#2]
我是在命令行使用mocha的. 会报找不到 .ajax的方法, 但是 jquery本身可以输出.
感谢.

**Comment by ruanyf** [comment]
如果是mocha的问题，参考一下教程库 https://github.com/ruanyf/mocha-demos

**Comment by kokokele** [comment]
上面的教程我都过了, 感谢分享. 
demo05 异步请求你是用的superagent. 我工作时用的是 jquery.ajax加载数据的. 本身代码运行正常.
但是mocha测试的时候找不到 jquery.ajax方法,但是可以找到jquery.(jquery的任何方法都是undefined.)

**Comment by kokokele** [comment]
补充一句 我也是用命令行测试的.

**Comment by ruanyf** [comment]
我猜需要jsdom模拟浏览器环境。

**Comment by kokokele** [comment]
恩, 发现.jquery初始化需要window.document.   感谢.
