### ISSUE TITLE
请教: react组件的测试(enzyme,chai,jsdom)

### ISSUE THREAD

**Issue by SansaZhang** [ruanyf/react-testing-demo#5]
您好  我在您的示例基础上react组件单元测试, 组件中用到了antd的组件, 比如Select标签点击出来列表不在我一开始mount的wrapper环境中, 我在wrapper上没办法取到这个元素, 没法在它的上面做模拟点击这种测试, 请教您应该怎么做这种带antd的react组件的测试呢? 我试了在document上可以取到但是原生的click()事件不起作用~

**Comment by ruanyf** [comment]
这个要把它渲染成真实 DOM，然后在真实 DOM 上测试点击事件。

**Comment by SansaZhang** [comment]
我是用enzyme mount方法渲染的, 据文档应该就是真实DOM啊?

**Comment by ruanyf** [comment]
你改用第一种方法，使用 React 的原生测试 Addon 试试。

**Comment by ctq123** [comment]
我也遇到类似的问题，antd+redux+enzyme，测试antd提供的Form组件时有问题了
A=Form.Create()(B)
想测试原生的B，可是B经过Form经过一层封装，里面的getFieldDecorator()函数又必须依赖Form创建完成后的A才行，因此mount(B)是编译不通过的，必须mount(A)才编译通过，可是我的期望是在编译期间设置B的props和context属性，来测试B的componentWillMount(里面用到props,context)，这样似乎没办法做到，太坑了。
是不是测试antd组件无法用enzyme测试?
